include: 'https://raw.githubusercontent.com/Nitrokey/common-ci-jobs/master/common_jobs.yml'

stages:
  - pull-github
  - build
  - deploy

variables:
  #Repo for shared scripts (pull.sh release.sh, nightly_upload.sh):
  GIT_STRATEGY: clone     #This seems to have no effect also set in webinterface
  GIT_DEPTH: 0          #This seems to have no effect also set in webinterface
  GIT_SUBMODULE_STRATEGY: recursive #This seems to have no effect also set in webinterfac
  SCRIPTS_REPO: git@git.dotplex.com:nitrokey/gitlab-ci.git
  REPO_USER: nitrokey
  REPO_NAME: heads
  MAIN_BRANCH: master
  DEVICE_FOLDER: "nitropad"
  COMMON_PULL: "true"
  COMMON_UPLOAD_NIGHTLY: "false"
  COMMON_GITHUB_RELEASE: "false"
  COMMON_UPLOAD_FILES: "true"
  UPLOAD_FOLDER: "heads"

build-heads-x230:
  image: registry.git.dotplex.com/nitrokey/heads/heads-build@sha256:3f482128cd7a4f788b6490e2cd74ed35d42d4f44c1fb1bef5e2f23e3a789e6ce
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  tags:
    - docker
  stage: build
  script: 
    - make BOARD=x230-hotp-verification
    - make BOARD=x230-flash
    - mkdir -p artifacts
    - find /builds/ -name "*.rom"
    - find /builds/ -name "*.npf"
    - find /builds/ -name "heads*.rom" -exec cp "{}"  artifacts/ \;
    - find /builds/ -name "*.npf" -exec cp "{}"  artifacts/ \;
  after_script:
    - wget $icon_server/checkmark/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA/$CI_JOB_NAME/$CI_JOB_STATUS/${CI_JOB_URL#*/*/*/}
  artifacts:
    paths:
      - artifacts
    expire_in: 30 hrs

build-heads-t430:
  image: registry.git.dotplex.com/nitrokey/heads/heads-build@sha256:3f482128cd7a4f788b6490e2cd74ed35d42d4f44c1fb1bef5e2f23e3a789e6ce
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  tags:
    - docker
  stage: build
  script: 
    - make BOARD=t430
    - make BOARD=t430-flash
    - mkdir -p artifacts
    - ls /builds/
    - find /builds/ -name "*.rom"
    - find /builds/ -name "*.npf"
    - find /builds/ -name "heads*.rom" -exec cp "{}"  artifacts/ \;
    - find /builds/ -name "*.npf" -exec cp "{}"  artifacts/ \;
  after_script:
    - wget $icon_server/checkmark/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA/$CI_JOB_NAME/$CI_JOB_STATUS/${CI_JOB_URL#*/*/*/}
  artifacts:
    paths:
      - artifacts
    expire_in: 30 hrs