
include:
  - project: 'nitrokey/gitlab-ci'
    file:
      - 'common-jobs/common_jobs.yml'

stages:
  - pull-github
  - build
  - deploy

variables:
  #Repo for shared scripts (pull.sh release.sh, nightly_upload.sh):
  GIT_STRATEGY: clone               #This seems to have no effect also set in webinterface
  GIT_DEPTH: 0                      #This seems to have no effect also set in webinterface
  GIT_SUBMODULE_STRATEGY: recursive #This seems to have no effect also set in webinterface
  REPO_NAME: heads
  MAIN_BRANCH: nitropad
  DEVICE_FOLDER: "nitropad"
  COMMON_PULL: "true"
  COMMON_UPLOAD_NIGHTLY: "false"
  COMMON_GITHUB_RELEASE: "true"
  COMMON_UPLOAD_FILES: "false"
  UPLOAD_FOLDER: "heads"


build-nitropad-firmwares:
  image: registry.git.nitrokey.com/nitrokey/heads/heads-build:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  tags:
    - docker
  stage: build
  script: 
    - ./create-release.sh
    - ls -la artifacts
  artifacts:
    paths:
      - artifacts
    expire_in: 30 hrs


